/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.CardLayout;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author Adriana
 */
public final class Frm_menuprincipal extends javax.swing.JFrame {

    /**
     * Creates new form Frm_menuprincipal
     */
    Frm_alta frm_alta = new Frm_alta();
    Frm_buscar frm_buscar = new Frm_buscar();
    Frm_eliminar frm_eliminar = new Frm_eliminar();
    Frm_modificacion frm_modificacion = new Frm_modificacion();
    Frm_retro frm_retro = new Frm_retro();

    
    CardLayout Vista; 
    
    public Frm_menuprincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        Vista = (CardLayout) pnl_Vista_Principal.getLayout(); 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_emisor = new javax.swing.JToggleButton();
        btn_divisor = new javax.swing.JToggleButton();
        btn_base = new javax.swing.JToggleButton();
        btn_salir = new javax.swing.JToggleButton();
        btn_fija = new javax.swing.JToggleButton();
        btn_retro = new javax.swing.JToggleButton();
        pnl_Vista_Principal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("POLARIZACIONES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 170, -1));

        btn_emisor.setBackground(new java.awt.Color(255, 255, 255));
        btn_emisor.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btn_emisor.setText("Emisor");
        btn_emisor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_emisor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_emisor.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_emisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emisorActionPerformed(evt);
            }
        });
        jPanel1.add(btn_emisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 230, 50));

        btn_divisor.setBackground(new java.awt.Color(255, 255, 255));
        btn_divisor.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btn_divisor.setText("Divisor de Voltaje");
        btn_divisor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_divisor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_divisor.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_divisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisorActionPerformed(evt);
            }
        });
        jPanel1.add(btn_divisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 230, 50));

        btn_base.setBackground(new java.awt.Color(255, 255, 255));
        btn_base.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btn_base.setText("Base Comun");
        btn_base.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_base.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_base.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_base.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baseActionPerformed(evt);
            }
        });
        jPanel1.add(btn_base, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 209, 60));

        btn_salir.setBackground(new java.awt.Color(255, 255, 255));
        btn_salir.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_salir.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 150, -1));

        btn_fija.setBackground(new java.awt.Color(255, 255, 255));
        btn_fija.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btn_fija.setText("Fija");
        btn_fija.setActionCommand("Polarizacion FIja");
        btn_fija.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_fija.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_fija.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_fija.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_fijaMouseClicked(evt);
            }
        });
        btn_fija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fijaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_fija, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 230, 60));
        btn_fija.getAccessibleContext().setAccessibleName("Polarizacion FIJA");

        btn_retro.setBackground(new java.awt.Color(255, 255, 255));
        btn_retro.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btn_retro.setText("Realimentacion");
        btn_retro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_retro.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_retro.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_retro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retroActionPerformed(evt);
            }
        });
        jPanel1.add(btn_retro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 220, 60));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 290, 620));

        pnl_Vista_Principal.setBackground(new java.awt.Color(204, 255, 255));
        pnl_Vista_Principal.setLayout(new java.awt.CardLayout());
        jPanel2.add(pnl_Vista_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 1000, 680));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1350, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_emisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emisorActionPerformed
        // TODO add your handling code here:
        
        if(btn_emisor.isSelected())
        {
            pnl_Vista_Principal.add(frm_eliminar, "eliminar");
            Vista.show(pnl_Vista_Principal, "eliminar");
            SwingUtilities.updateComponentTreeUI(this); 
            this.repaint();
        }else{
            pnl_Vista_Principal.removeAll(); 
        }
        
    }//GEN-LAST:event_btn_emisorActionPerformed

    private void btn_divisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisorActionPerformed
        // TODO add your handling code here:
        
        if(btn_divisor.isSelected()){
            pnl_Vista_Principal.add(frm_modificacion, "modificacion");
            Vista.show(pnl_Vista_Principal, "modificacion");
            SwingUtilities.updateComponentTreeUI(this); 
            this.repaint();
        }else{
            pnl_Vista_Principal.removeAll();
        }
        
    }//GEN-LAST:event_btn_divisorActionPerformed

    private void btn_baseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baseActionPerformed
        // TODO add your handling code here:
         if(btn_base.isSelected()){
        
        pnl_Vista_Principal.add(frm_buscar, "buscar");
        Vista.show(pnl_Vista_Principal, "buscar");
        SwingUtilities.updateComponentTreeUI(this); 
        this.repaint();
         }else{
             pnl_Vista_Principal.removeAll();
         }
    }//GEN-LAST:event_btn_baseActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0); 
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_fijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fijaActionPerformed
        // TODO add your handling code here:
        pnl_Vista_Principal.add(frm_alta, "alta");
        Vista.show(pnl_Vista_Principal, "alta");
        SwingUtilities.updateComponentTreeUI(this); 
        this.repaint();
    }//GEN-LAST:event_btn_fijaActionPerformed

    private void btn_retroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retroActionPerformed
        // TODO add your handling code here:
         pnl_Vista_Principal.add(frm_retro, "Realimentacion");
        Vista.show(pnl_Vista_Principal, "Realimentacion");
        SwingUtilities.updateComponentTreeUI(this); 
        this.repaint();
    }//GEN-LAST:event_btn_retroActionPerformed

    private void btn_fijaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fijaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_fijaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_menuprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_base;
    private javax.swing.JToggleButton btn_divisor;
    private javax.swing.JToggleButton btn_emisor;
    private javax.swing.JToggleButton btn_fija;
    private javax.swing.JToggleButton btn_retro;
    private javax.swing.JToggleButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnl_Vista_Principal;
    // End of variables declaration//GEN-END:variables

    
}
