/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import veterinaria.Circuito;

/**
 *
 * @author Adriana
 */
public class Frm_eliminar extends javax.swing.JPanel {

    /**
     * Creates new form Frm_eliminar
     */
    
    //variables 
    public double rb;
    public double vcc;
    public double rc;
    public double vbb; 
    public double b;
    public double r1;  
    public double r2; 
    public double re; 
    final double vbe=0.7;
    
    public Frm_eliminar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        In_vcc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        In_RB = new javax.swing.JTextField();
        In_RC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        In_VBB = new javax.swing.JTextField();
        In_B = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        In_RE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        label_ib = new javax.swing.JLabel();
        label_ic = new javax.swing.JLabel();
        label_ie = new javax.swing.JLabel();
        label_vce = new javax.swing.JLabel();
        label_vrc = new javax.swing.JLabel();
        label_vrb = new javax.swing.JLabel();
        label_vre = new javax.swing.JLabel();
        label_vb = new javax.swing.JLabel();
        label_vc = new javax.swing.JLabel();
        label_ve = new javax.swing.JLabel();
        label_icsat = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        label_vceq = new javax.swing.JLabel();
        label_icq = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("POLARIZACION FIJA EN RESISTENCIA DEL EMISOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 32, 630, 53));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Insertar Datos del Circuito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PolFijaRE.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 24, -1, 386));

        In_vcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                In_vccActionPerformed(evt);
            }
        });
        jPanel2.add(In_vcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 76, 46, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel4.setText("VCC: ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 78, -1, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setText("RB: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 105, -1, -1));
        jPanel2.add(In_RB, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 103, 48, -1));

        In_RC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                In_RCActionPerformed(evt);
            }
        });
        jPanel2.add(In_RC, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 129, 46, -1));

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel5.setText("RC: ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 131, -1, -1));

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel6.setText("VBB: ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 191, -1, -1));
        jPanel2.add(In_VBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 189, 46, -1));
        jPanel2.add(In_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 220, 46, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel7.setText("B: ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel8.setText("RE: ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 161, -1, -1));

        In_RE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                In_REActionPerformed(evt);
            }
        });
        jPanel2.add(In_RE, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 158, 46, -1));

        jLabel9.setText("Ib=");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 263, -1, -1));

        jLabel10.setText("Ic=");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 283, -1, -1));

        jLabel11.setText("Ie=");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 303, -1, -1));

        jLabel12.setText("Vce=");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 323, -1, -1));

        jLabel13.setText("Vrc=");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 343, -1, -1));

        jLabel14.setText("Vrb=");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 363, -1, -1));

        jLabel15.setText("Vre=");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 263, -1, -1));

        jLabel16.setText("Vb=");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 283, -1, -1));

        jLabel17.setText("Vc=");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 303, -1, -1));

        jLabel18.setText("Ve=");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 323, -1, -1));

        jLabel19.setText("Icsat=");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 343, -1, -1));

        label_ib.setText(".");
        jPanel2.add(label_ib, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 263, -1, -1));

        label_ic.setText(".");
        jPanel2.add(label_ic, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 283, -1, -1));

        label_ie.setText(".");
        jPanel2.add(label_ie, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 303, -1, -1));

        label_vce.setText(".");
        jPanel2.add(label_vce, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 323, -1, -1));

        label_vrc.setText(".");
        jPanel2.add(label_vrc, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 343, -1, -1));

        label_vrb.setText(".");
        jPanel2.add(label_vrb, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 363, -1, -1));

        label_vre.setText(".");
        jPanel2.add(label_vre, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 263, -1, -1));

        label_vb.setText(".");
        jPanel2.add(label_vb, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 283, -1, -1));

        label_vc.setText(".");
        jPanel2.add(label_vc, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 303, -1, -1));

        label_ve.setText(".");
        jPanel2.add(label_ve, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 323, -1, -1));

        label_icsat.setText(".");
        jPanel2.add(label_icsat, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 343, -1, -1));

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check.png"))); // NOI18N
        btn_guardar.setToolTipText("");
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
        });
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, 68, 67));

        btn_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        btn_borrar.setToolTipText("");
        btn_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_borrarMouseClicked(evt);
            }
        });
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, 77, 69));

        jLabel20.setText("Vceq=");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 363, -1, -1));

        jLabel21.setText("Icq=");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 383, -1, -1));

        label_vceq.setText(".");
        jPanel2.add(label_vceq, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 363, -1, -1));

        label_icq.setText(".");
        jPanel2.add(label_icq, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 383, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 960, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void In_vccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_In_vccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_In_vccActionPerformed

    private void In_RCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_In_RCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_In_RCActionPerformed

    private void In_REActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_In_REActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_In_REActionPerformed

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
       
       vcc = Double.parseDouble(In_vcc.getText());
        System.out.println(In_vcc);
        rb = Double.parseDouble(In_RB.getText());
        re = Double.parseDouble(In_RE.getText());
        rc = Double.parseDouble(In_RC.getText());
        vbb = Double.parseDouble(In_VBB.getText());
        b = Double.parseDouble(In_B.getText());
        
        System.out.println(rb);
        System.out.println(rc);
        System.out.println(vbb);
        System.out.println(b);
        System.out.println("valores recuperados");
        Circuito circ2 = new Circuito(vcc,rb,rc,vbb,b,0,0,re);
        circ2.PofEM();
        circ2.cadenas();
        
        label_ib.setText(circ2.imp_ib);
        label_ic.setText(circ2.imp_ic);
        label_ie.setText(circ2.imp_ie);
        label_vce.setText(circ2.imp_vce);
        label_vrc.setText(circ2.imp_vrc);
        label_vrb.setText(circ2.imp_vrb);
        label_vre.setText(circ2.imp_vre);
        label_vb.setText(circ2.imp_vb);
        label_vc.setText(circ2.imp_vc);
        label_ve.setText(circ2.imp_ve);
        label_icsat.setText(circ2.imp_icsat);
        label_vceq.setText(circ2.imp_vceq);
        label_icq.setText(circ2.imp_icq); 
    }//GEN-LAST:event_btn_guardarMouseClicked

    private void btn_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_borrarMouseClicked
        // TODO add your handling code here:
        In_B.setText("");
       In_RB.setText("");
       In_vcc.setText("");
       In_RC.setText("");
       In_RE.setText("");
       In_vcc.setText("");
       In_VBB.setText("");
    }//GEN-LAST:event_btn_borrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField In_B;
    private javax.swing.JTextField In_RB;
    private javax.swing.JTextField In_RC;
    private javax.swing.JTextField In_RE;
    private javax.swing.JTextField In_VBB;
    private javax.swing.JTextField In_vcc;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_ib;
    private javax.swing.JLabel label_ic;
    private javax.swing.JLabel label_icq;
    private javax.swing.JLabel label_icsat;
    private javax.swing.JLabel label_ie;
    private javax.swing.JLabel label_vb;
    private javax.swing.JLabel label_vc;
    private javax.swing.JLabel label_vce;
    private javax.swing.JLabel label_vceq;
    private javax.swing.JLabel label_ve;
    private javax.swing.JLabel label_vrb;
    private javax.swing.JLabel label_vrc;
    private javax.swing.JLabel label_vre;
    // End of variables declaration//GEN-END:variables
}
