/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;



import java.awt.event.*;
import java.net.URL;
import javax.swing.ImageIcon;


import javax.swing.*;
import veterinaria.Circuito;

/**
 *
 * @author Adriana
 */
public class Frm_alta extends javax.swing.JPanel {

    /**
     * Creates new form Frm_alta
     */
    //VARIABLES
    public double rb;
    public double vcc;
    public double rc;
    public double vbb; 
    public double b;
    public double r1;  
    public double r2; 
    public double re; 
    final double vbe=0.7;
    
    
    
   
    
    
    public Frm_alta() {
          
        initComponents();
    }

    public void numeros(JTextField a){
        a.addKeyListener(new KeyAdapter(){
            public void KeyTyped(KeyEvent e){
                char c = e.getKeyChar();
                if(!Character.isDigit(c) && c!='.'){
                    e.consume();
                }
                if(c == '.' && In_vcc.getText().contains(".")){
                    e.consume();
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_guardar = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        In_vcc = new javax.swing.JTextField();
        In_RB = new javax.swing.JTextField();
        In_RC = new javax.swing.JTextField();
        In_VBB = new javax.swing.JTextField();
        In_B = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        label_ib = new javax.swing.JLabel();
        label_ic = new javax.swing.JLabel();
        label_ie = new javax.swing.JLabel();
        label_vce = new javax.swing.JLabel();
        label_vrc = new javax.swing.JLabel();
        label_vrb = new javax.swing.JLabel();
        label_vre = new javax.swing.JLabel();
        label_vb = new javax.swing.JLabel();
        label_vc = new javax.swing.JLabel();
        label_ve = new javax.swing.JLabel();
        label_icsat = new javax.swing.JLabel();
        label_vceq = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        label_icq = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "inserte datos de la mascota", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Nombre (Dueño): ");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Nombre Mascota: ");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Apellido Paterno (DUEÑO): ");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("Apellido Materno (DUEÑO): ");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setText("Direccion:");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("Telefono:");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setText("Tipo de Mascota:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "inserte datos de la mascota", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setText("Nombre (Dueño): ");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setText("Nombre Mascota: ");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setText("Apellido Paterno (DUEÑO): ");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setText("Apellido Materno (DUEÑO): ");

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setText("Direccion:");

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setText("Telefono:");

        jLabel22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel22.setText("Tipo de Mascota:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(jLabel16)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(15, 15, 15)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel34.setText("jLabel34");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("POLARIZACION FIJA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 278, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inserte Datos de los Circuitos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check.png"))); // NOI18N
        btn_guardar.setToolTipText("");
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
        });
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 74, 69));

        btn_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        btn_borrar.setToolTipText("");
        btn_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_borrarMouseClicked(evt);
            }
        });
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 77, 69));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PolFija.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 24, 560, 376));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setText("RB: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 64, -1, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel4.setText("VCC: ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 37, -1, -1));

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel5.setText("RC: ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel6.setText("VBB: ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 116, -1, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel7.setText("B: ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 145, -1, -1));

        In_vcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                In_vccActionPerformed(evt);
            }
        });
        jPanel2.add(In_vcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 35, 61, -1));
        jPanel2.add(In_RB, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 62, 63, -1));

        In_RC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                In_RCActionPerformed(evt);
            }
        });
        jPanel2.add(In_RC, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 88, 61, -1));
        jPanel2.add(In_VBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 114, 61, -1));
        jPanel2.add(In_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 145, 61, -1));

        jLabel8.setText("Ib=");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 225, -1, -1));

        jLabel23.setText("Ic=");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 257, -1, -1));

        jLabel24.setText("Ie=");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 277, -1, -1));

        jLabel25.setText("Vce=");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 297, -1, -1));

        jLabel26.setText("Vrc=");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 317, -1, -1));

        jLabel27.setText("Vrb=");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 337, -1, -1));

        jLabel28.setText("Vre=");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, -1, -1));

        jLabel29.setText("Vb=");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, -1, -1));

        jLabel30.setText("Vc=");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 260, -1, -1));

        jLabel31.setText("Ve=");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, -1, -1));

        jLabel32.setText("Icsat=");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, -1, -1));

        jLabel33.setText("Vceq=");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, -1, -1));

        label_ib.setBackground(new java.awt.Color(255, 153, 204));
        label_ib.setText(".");
        jPanel2.add(label_ib, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 225, -1, -1));

        label_ic.setBackground(new java.awt.Color(255, 102, 102));
        label_ic.setText(".");
        jPanel2.add(label_ic, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, -1, -1));

        label_ie.setText(".");
        jPanel2.add(label_ie, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 277, -1, -1));

        label_vce.setText(".");
        jPanel2.add(label_vce, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 297, -1, -1));

        label_vrc.setText(".");
        jPanel2.add(label_vrc, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 317, -1, -1));

        label_vrb.setText(".");
        jPanel2.add(label_vrb, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 337, -1, -1));

        label_vre.setText(".");
        jPanel2.add(label_vre, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 220, -1, -1));

        label_vb.setText(".");
        jPanel2.add(label_vb, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, -1, -1));

        label_vc.setText(".");
        jPanel2.add(label_vc, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, -1, -1));

        label_ve.setText(".");
        jPanel2.add(label_ve, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, -1, -1));

        label_icsat.setText(".");
        jPanel2.add(label_icsat, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, -1, -1));

        label_vceq.setText(".");
        jPanel2.add(label_vceq, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 320, -1, -1));

        jLabel35.setText("Icq=");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, -1, -1));

        label_icq.setText(".");
        jPanel2.add(label_icq, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 960, 590));
        jPanel2.getAccessibleContext().setAccessibleName("Inserte datos de la mascota");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void In_RCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_In_RCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_In_RCActionPerformed

    private void In_vccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_In_vccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_In_vccActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        // TODO add your handling code here:
        
        
        vcc = Double.parseDouble(In_vcc.getText());
        System.out.println(vcc);
        rb = Double.parseDouble(In_RB.getText());
        rc = Double.parseDouble(In_RC.getText());
        vbb = Double.parseDouble(In_VBB.getText());
        b = Double.parseDouble(In_B.getText());
        System.out.println(rb);
        System.out.println(rc);
        System.out.println(vbb);
        System.out.println(b);
        System.out.println("valores recuperados");
        Circuito circ1 = new Circuito(vcc,rb,rc,vbb,b,0,0,0);
        circ1.PolFija();
        circ1.cadenas();
        label_ib.setText(circ1.imp_ib);
        label_ic.setText(circ1.imp_ic);
        label_ie.setText(circ1.imp_ie);
        label_vce.setText(circ1.imp_vce);
        label_vrc.setText(circ1.imp_vrc);
        label_vrb.setText(circ1.imp_vrb);
        label_vre.setText(circ1.imp_vre);
        label_vb.setText(circ1.imp_vb);
        label_vc.setText(circ1.imp_vc);
        label_ve.setText(circ1.imp_ve);
        label_icsat.setText(circ1.imp_icsat);
        label_vceq.setText(circ1.imp_vceq);

        /*
        System.out.println("Vb= "+circ1.vb);
        System.out.println("Ve= "+circ1.ve);
        System.out.println("Ie= "+circ1.ie);
        System.out.println("Ib= "+circ1.ib);
        System.out.println("Ic= "+circ1.ic);
        System.out.println("Vceq= "+circ1.vceq);
        System.out.println("Icq= "+circ1.icq);
        System.out.println("Vce= "+circ1.vce);
        System.out.println("Vrc= "+circ1.vrc);
        System.out.println("Vc= "+circ1.vc);
        System.out.println("Icsat= "+circ1.icsat);
        System.out.println("Vre= "+circ1.vre);*/

    }//GEN-LAST:event_btn_guardarMouseClicked

    private void btn_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_borrarMouseClicked
        // TODO add your handling code here:
        In_B.setText("");
       In_RB.setText("");
       In_VBB.setText("");
       In_RC.setText("");
       //In_RE.setText("");
       In_vcc.setText("");
    }//GEN-LAST:event_btn_borrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField In_B;
    private javax.swing.JTextField In_RB;
    private javax.swing.JTextField In_RC;
    private javax.swing.JTextField In_VBB;
    private javax.swing.JTextField In_vcc;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel label_ib;
    private javax.swing.JLabel label_ic;
    private javax.swing.JLabel label_icq;
    private javax.swing.JLabel label_icsat;
    private javax.swing.JLabel label_ie;
    private javax.swing.JLabel label_vb;
    private javax.swing.JLabel label_vc;
    private javax.swing.JLabel label_vce;
    private javax.swing.JLabel label_vceq;
    private javax.swing.JLabel label_ve;
    private javax.swing.JLabel label_vrb;
    private javax.swing.JLabel label_vrc;
    private javax.swing.JLabel label_vre;
    // End of variables declaration//GEN-END:variables
}
